[hololens]
package = "holo/lens-sencha-app"

[hololens.sencha]
app = "EmergenceContentEditor"

[hololens.input]
root = "sencha-workspace"
files = [
    "EmergenceContentEditor/**",
    "packages/emr-skeleton-theme/**",
    "packages/emergence-cms/**",
    "packages/emergence-apikit/**",
    "packages/jarvus-apikit/**",
    "packages/jarvus-fileupload/**",
    "packages/jarvus-hotfixes/**",
    "ext/**",
    "workspace.json",
]

[hololens.output]
root = "webapp-builds/EmergenceContentEditor"
merge = "replace"
