<?php

Git::$repositories['slate'] = [
    'remote' => 'https://github.com/SlateFoundation/slate.git',
    'originBranch' => 'development',
    'workingBranch' => 'development',
    'localOnly' => true,
    'trees' => [
        'dwoo-plugins',
        'event-handlers',
        'html-templates' => [
            'exclude' => [
                '#^/app/SlateAdmin(/|$)#' // don't delete file from slate-admin package
            ]
        ],
        'mail-handlers',
        'php-classes',
        'php-config',
        'php-migrations',
        'phpunit-tests',
        'sencha-workspace/pages',
        'site-root' => [
            'exclude' => [
                '#/manage.php$#', // don't delete file from slate-admin package
                '#^/css(/|$)#', // don't sync /css, this directory is generated by /sass/compile
                '#^/js/pages(/|$)#' // don't sync /js/pages, this directory is generated by /sencha-cmd/pages-build
            ]
        ],

        // added to keep track of skeleton-v2 overrides
        'sencha-workspace/packages/emergence-cms',
        'sencha-workspace/ContentEditor'
    ]
];