<?php

Git::$repositories['slate'] = [
    'remote' => 'https://github.com/SlateFoundation/slate.git',
    'originBranch' => 'development',
    'workingBranch' => 'development',
    'trees' => [
        'content-blocks',
        'dwoo-plugins',
        'event-handlers',
        'html-templates' => [
            'exclude' => [
                // from slate-admin layer:
                '#^/app/SlateAdmin(/|$)#'
            ]
        ],
        'mail-handlers',
        'php-classes' => [
            'exclude' => [
                // from emergence-saml2 layer:
                '#^/Emergence/Connectors/SAML2\.php$#',
                '#^/Emergence/SAML2/Container\.php$#',

                // from simplesamlphp-saml2 layer:
                '#^/SAML2(/|$)#',

                // from xmlseclibs layer:
                '#^/RobRichards(/|$)#'
            ]
        ],
        'php-config' => [
            'exclude' => [
                '#^/Site.config.d(/|$)#', // don't sync local site config

                // from emergence-saml2 layer:
                '#^/Emergence/Connectors/SAML2\.config\.php$#',
                '#^/SAML2/Compat/ContainerSingleton\.config\.php$#',
                '#^/TableManagerRequestHandler\.config\.d/emergence-saml2\.php$#',
                '#^/Git\.config\.d/simplesamlphp-saml2\.php$#',
                '#^/Git\.config\.d/xmlseclibs\.php$#'
            ]
        ],
        'php-migrations',
        'phpunit-tests',
        'sencha-workspace/pages',
        'site-root' => [
            'exclude' => [
                '#^/css(/|$)#', // don't sync /css, this directory is generated by /sass/compile
                '#^/js/pages(/|$)#', // don't sync /js/pages, this directory is generated by /sencha-cmd/pages-build

                // from slate-admin layer:
                '#/manage\.php$#',

                // from emergence-saml2 layer:
                '#/connectors/saml2\.php$#'
            ]
        ],

        // added to keep track of skeleton-v2 overrides
        'sencha-workspace/packages/emergence-cms',
        'sencha-workspace/ContentEditor'
    ]
];