<?php

Git::$repositories['slate'] = [
    'remote' => 'https://github.com/SlateFoundation/slate.git',
    'originBranch' => 'develop',
    'workingBranch' => 'develop',
    'trees' => [
        'content-blocks',
        'event-handlers',
        'html-templates' => [
            'exclude' => [
                // from slate-admin layer:
                '#^/webapps/SlateAdmin(/|$)#'
            ]
        ],
        'php-classes' => [
            'exclude' => [
                // from slate-admin layer:
                '#^/SlateAdmin(/|$)#',

                // from emergence-saml2 layer:
                '#^/Emergence/SAML2(/|$)#',

                // from simplesamlphp-saml2 layer:
                '#^/SAML2(/|$)#',

                // from xmlseclibs layer:
                '#^/RobRichards(/|$)#'
            ]
        ],
        'php-config' => [
            'exclude' => [
                '#^/Site.config.d(/|$)#', // don't sync local site config

                // from emergence-saml2 layer:
                '#^/Emergence/SAML2(/|$)#',
                '#^/SAML2/Compat/ContainerSingleton\.config\.php$#',
                '#^/TableManagerRequestHandler\.config\.d/emergence-saml2\.php$#',
                '#^/Git\.config\.d/simplesamlphp-saml2\.php$#',
                '#^/Git\.config\.d/xmlseclibs\.php$#'
            ]
        ],
        'php-migrations',
        'sencha-workspace/EmergenceContentEditor/local.properties',
        'sencha-workspace/pages',
        'site-root' => [
            'exclude' => [
                '#^/css(/|$)#', // don't sync /css, this directory is generated by /sass/compile
                '#^/js/pages(/|$)#', // don't sync /js/pages, this directory is generated by /sencha-cmd/pages-build

                // from slate-admin layer:
                '#/manage\.php$#',

                // from emergence-saml2 layer:
                '#/connectors/saml2\.php$#'
            ]
        ]
    ]
];