[holomapping]
files = [
    "*/**",

    # exclude CI and developer assets
    "!.github/",
    "!.vscode/",
    "!docs/",
    "!fixtures/",
    "!habitat/",
    "!helm-chart/",
    "!php-config/Git.config.d/",
    "!script/",

    # exclude submodules that support local Sencha app development
    "!sencha-workspace/ext",
    "!sencha-workspace/packages.remote/*"
]
after = "*"
