apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "slate.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "slate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slate.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always

      containers:
      - image: {{ .Values.image }}
        name: {{ .Release.Name }}-app
        imagePullPolicy: Always

        env:
          - name: HAB_SLATE_COMPOSITE
            value: |
              [services.mysql]
              pkg_ident = {{ .Values.hab.composite.mysql.pkg_ident | quote }}

          - name: HAB_MYSQL
            value: |
            {{- if .Values.hab.mysql }}
              {{- range $key, $value := .Values.hab.mysql }}
              {{ $key }} = {{ $value | quote }}
              {{- end }}
            {{- end }}

        ports:
        - containerPort: 80
          name: http
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "slate.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "slate.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 80
    protocol: TCP
---


apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "slate.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    {{- include "slate.cert-manager-annotations" . | nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Release.Name }}-tls
  backend:
    serviceName: {{ .Release.Name }}
    servicePort: 80
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
