{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "site.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
  - hosts:
    - {{ .Values.site.canonicalHostname | quote }}
    {{- range .Values.ingress.secondaryHostnames }}
    - {{ . | quote}}
    {{- end }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.site.canonicalHostname | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}-site
          servicePort: 80
  {{- range .Values.ingress.secondaryHostnames }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Release.Name }}-site
          servicePort: 80
  {{- end }}
{{- end }}
