name: K8s PR Sandbox Destroy

on:
  pull_request:
    branches: [develop]
    types: [closed]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  KUBE_NAMESPACE: ${{ secrets.kube_namespace }}
  KUBE_CONFIG_DATA: ${{ secrets.kube_config }}

  PR_NAME: pr-${{ github.event.number }}

jobs:

  k8s-destroy:
    runs-on: ubuntu-latest
    steps:

    - name: Add kubeconfig to environment
      run: |
        set -e
        test -e ~/.kube || mkdir ~/.kube
        cat <<EOF > ~/.kube/config
        $(printf '%s' "$KUBE_CONFIG_DATA" | base64 -d)
        EOF

    - uses: azure/setup-kubectl@v1

    - name: Delete PR Deployment
      run: |
        set -e
        kubectl config set-context --current --namespace="${KUBE_NAMESPACE}"
        kubectl delete all,ingress -l "app.kubernetes.io/instance=${PR_NAME}"
        kubectl delete secret "${PR_NAME}-tls"
